name: Continuous Delivery Simulation with Error

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Simulate Build
        run: |
          echo "Building the application..."
          mkdir build
          echo "Hello, CD!" > build/index.html
          echo "This is another file" > build/another.html

      - name: Simulate Deployment
        run: |
          echo "Deploying to fake server..."
          mkdir /tmp/fake-server
          cp -r build/* /tmp/fake-server/
          echo "Deployment complete. Files are now available in /tmp/fake-server"

      - name: Simulate Post-Deployment Test
        run: |
          echo "Running post-deployment tests..."
          if [ ! -f /tmp/fake-server/missing-file.html ]; then
            echo "ERROR: Critical file missing in deployment!" >&2
            exit 1
          fi
          echo "All files are present. Deployment successful."
